### ISSUE TITLE
[1.9] 0 Chunks, can't increase radius

### ISSUE THREAD

**Issue by CA2020** [TheCBProject/ChickenChunks#1]
Using Forge 1863 and mod version 1.9-2.0.1.1 with Core 1.9-2.0.1.6 and Lib 1.9-2.0.1.6
When you place a Chunk Loader down, it's default to 0 chunks and you cant increase them.

Also the Lib file gets deleted from the mods folder, is that intended?

**Comment by covers1624** [comment]
Can i have a screen shot? It works fine for me.. Lib gets auto moved to mods/<mcversion>/

**Comment by covers1624** [comment]
Also can you put your log up as well please. 

----- Original Message -----
From: "TheCBProject/ChickenChunks" 
To:"TheCBProject/ChickenChunks" 
Cc:
Sent:Tue, 12 Apr 2016 15:53:48 -0700
Subject:[TheCBProject/ChickenChunks] [1.9] 0 Chunks, can't increase
radius (#1)

	Using Forge 1863 and mod version 1.9-2.0.1.1 with Core 1.9-2.0.1.6
and Lib 1.9-2.0.1.6
 When you place a Chunk Loader down, it's default to 0 chunks and you
cant increase them. 

	Also the Lib file gets deleted from the mods folder, is that
intended? 

	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub [1]     

Links:
------
[1] https://github.com/TheCBProject/ChickenChunks/issues/1

**Comment by CA2020** [comment]
Sure. This is what I'm using.
http://i.imgur.com/XnczsMm.png

This is show on console when a Chunk loader is placed down.
http://pastebin.com/3ukhdkEr

And this time was worst, it directly crashed when I right click on the Chunk Loader, producing this crash:
http://pastebin.com/CXP75Qip

**Comment by covers1624** [comment]
Try back dating forge to 1858 ill push an update soon to everything for the new forge

**Comment by CA2020** [comment]
Using 1858, same crash.
http://pastebin.com/z7inWLrX

Then updated both the Core and the Lib to the new ones on curse and still same crash using forge 1858
http://pastebin.com/tJ7RECFB
or 1863
http://pastebin.com/N05X8Yu6

An update that works with 1863 would be great indeed as apparently Forge has been stuck in that version for a couple of days already ;)

Thanks for your time, and also thanks for taking this project in your hand :D We all like this Chunk Loaders we grow with lol

**Comment by covers1624** [comment]
alright ill get right on it. No problem ive always loved cb's mods and having the opportunity to continue them is a real honor. EnderStorage should be out in a few days just need to rewrite some of the fluid handling then the ender pouch(easy bit).

**Comment by covers1624** [comment]
Found the issue, The dep downloader is downloading a really old version of lib

**Comment by covers1624** [comment]
Can you verify it is fixed with this CCC Version: http://adel.podgeweb.com:8080/job/CodeChicken%20Core/10/

**Comment by CA2020** [comment]
Yeah Baby Ender Storage and the Pouch gonna be back :D Can't wait... Thanks a lot.

PS: Should I only install Chicken Chunks and the Core, or I also have to place the Lib and let the mod move it on launch?

**Comment by CA2020** [comment]
Ok Tested, but no luck, the crash is gone, but still can't increase the radius.
Maybe this is one of the errors:
[19:37:50] [CodeChicken Update Checker/ERROR]: Failed to check update for ChickenChunks returned: Err: Unknown mod/version
[19:37:50] [CodeChicken Update Checker/ERROR]: Failed to check update for CodeChickenCore returned: Err: Unknown mod/version

Here the log: Those chunks of errors show each time you press the + button to increase the radius.

http://pastebin.com/K3gUzPeN

**Comment by covers1624** [comment]
Those update checker lines are simply just the CCC Update checker
unable to find an update on chickenbones.net and is nothing to be
concerned about. The log on the other hand once i get back from school
ill take a look at that one. The interesting thing is that i can
increase it fine in dev, but it has been demonstrated many times that
what works in dev wont usually work outside of dev.

----- Original Message -----

**Comment by covers1624** [comment]
Can you please try with the latest version on curse.

**Comment by CA2020** [comment]
Ok trying:
ChickenChunks-1.9-2.0.1.22-universal
CodeChickenCore-1.9-2.0.1.52-universal
CodeChickenLib-1.9-2.0.1.21-universal

First error is this one: (It wants the 1.9-2.0.1.22 Library and not the 21 that is on Curse)
http://i.imgur.com/Op6XhM9.png
And the log:
http://pastebin.com/pqLcuMxv

Going to http://adel.podgeweb.com:1616/maven/codechinken/CodeChickenLib/1.9-2.0.1.22//CodeChickenLib-1.9-2.0.1.22-universal.jar results in 404 Not Found

**Comment by covers1624** [comment]
Grab this build http://chickenbones.net/maven/codechicken/CodeChickenLib/1.9-2.0.1.23/

**Comment by CA2020** [comment]
On placing a Chunk Loader, this shows on the console:
`[11:39:37] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: codechicken.chunkloader.tile.TileChunkLoader.getWorld()Lnet/minecraft/world/World;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) [byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.AbstractMethodError: codechicken.chunkloader.tile.TileChunkLoader.getWorld()Lnet/minecraft/world/World;
	at codechicken.chunkloader.manager.ChunkLoaderManager.canLoaderAdd(ChunkLoaderManager.java:671) ~[ChunkLoaderManager.class:?]
	at codechicken.chunkloader.tile.TileChunkLoader.setShapeAndRadius(TileChunkLoader.java:55) ~[TileChunkLoader.class:?]
	at codechicken.chunkloader.tile.TileChunkLoader.activate(TileChunkLoader.java:119) ~[TileChunkLoader.class:?]
	at codechicken.chunkloader.tile.TileChunkLoaderBase.onBlockPlacedBy(TileChunkLoaderBase.java:98) ~[TileChunkLoaderBase.class:?]
	at codechicken.chunkloader.block.BlockChunkLoader.func_180633_a(BlockChunkLoader.java:122) ~[BlockChunkLoader.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:171) ~[acc.class:?]
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:53) ~[acc.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:719) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:141) ~[adq.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:471) ~[ls.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:680) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:55) ~[jg.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:11) ~[jg.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more`

Still can't increase radius, each time I try this shows on console:

> [11:40:17] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: codechicken.chunkloader.tile.TileChunkLoader.getWorld()Lnet/minecraft/world/World;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) [byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.AbstractMethodError: codechicken.chunkloader.tile.TileChunkLoader.getWorld()Lnet/minecraft/world/World;
	at codechicken.chunkloader.manager.ChunkLoaderManager.canLoaderAdd(ChunkLoaderManager.java:671) ~[ChunkLoaderManager.class:?]
	at codechicken.chunkloader.tile.TileChunkLoader.setShapeAndRadius(TileChunkLoader.java:55) ~[TileChunkLoader.class:?]
	at codechicken.chunkloader.network.ChunkLoaderSPH.handleChunkLoaderChangePacket(ChunkLoaderSPH.java:38) ~[ChunkLoaderSPH.class:?]
	at codechicken.chunkloader.network.ChunkLoaderSPH.handlePacket(ChunkLoaderSPH.java:26) ~[ChunkLoaderSPH.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:127) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler$1.run(PacketCustom.java:123) ~[PacketCustom$ServerInboundHandler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more
[11:40:18] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: codechicken.chunkloader.tile.TileChunkLoader.getWorld()Lnet/minecraft/world/World;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:664) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) [byn.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.AbstractMethodError: codechicken.chunkloader.tile.TileChunkLoader.getWorld()Lnet/minecraft/world/World;
	at codechicken.chunkloader.manager.ChunkLoaderManager.canLoaderAdd(ChunkLoaderManager.java:671) ~[ChunkLoaderManager.class:?]
	at codechicken.chunkloader.tile.TileChunkLoader.setShapeAndRadius(TileChunkLoader.java:55) ~[TileChunkLoader.class:?]
	at codechicken.chunkloader.network.ChunkLoaderSPH.handleChunkLoaderChangePacket(ChunkLoaderSPH.java:38) ~[ChunkLoaderSPH.class:?]
	at codechicken.chunkloader.network.ChunkLoaderSPH.handlePacket(ChunkLoaderSPH.java:26) ~[ChunkLoaderSPH.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:127) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler$1.run(PacketCustom.java:123) ~[PacketCustom$ServerInboundHandler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[g.class:?]
	... 5 more

**Comment by covers1624** [comment]
actualy wait, new build of CCC will be on curse shortly

**Comment by CA2020** [comment]
Ok, will keep an eye on it and give it a try again ;)

Gonna create a fresh new 1.9 environment just in case with Forge 1863 or 1864 _I guess those will be ok, right?

**Comment by covers1624** [comment]
yeah i use 1864 in dev

**Comment by CA2020** [comment]
Thanks a lot, it all works with this combination
ChickenChunks-1.9-2.0.1.25-universal
CodeChickenCore-1.9-2.0.1.53-universal
CodeChickenLib-1.9-2.0.1.23-universal

Including the spinning thingy on top of the Chunk loader ;)

**Comment by covers1624** [comment]
Yeah i found the issue, it seems that MCP mappings caused the issue, in 1.7 there was a method in tileentites called getWorldObj now it is called getWorld witch clashes with a function in the chunkloaders causing it to crash outside of dev because those getWorld methods were being renamed because of mcp causing them to not be implemented.
